"""empty message

Revision ID: d27a2a4393e3
Revises: 58bc2a708074
Create Date: 2021-07-17 06:39:31.227821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27a2a4393e3'
down_revision = '58bc2a708074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('alldone', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'alldone')
    # ### end Alembic commands ###
